const en = {
  internal_error: "Internal error",
  english: "English",
  hebrew: "Hebrew",
  login: "Login",
  home: "Home",
  files: "Files",
  register: "Register",
  logout: "Logout",
  logging_out: "Logging out",
  email: "Email",
  password: "Password",
  confirm_password: "Confirm password",
  not_found: "Not found",
  error: "Error",
  success: "Success",
  user_registered_successfully: "User registered successfully",
  user_login_successful: "User logged in successfully",
  user_logout_successful: "User logged out successfully",
  yes: "yes",
  no: "no",
  wont_share_email: "We'll never share your email.",
  error_occurred_refresh_page: "An error occurred. Please refresh this page",
  select_language: "Select language",
  passwords_dont_match: "Password dont match",
  information: "Information",
}
export default en;