const he = {
  internal_error: "שגיאה פנימית",
  english: "אנגלית",
  hebrew: "עברית",
  login: "התחברות",
  home: "בית",
  files: "קבצים",
  register: "הרשמה",
  logout: "התנתקות",
  logging_out: "מתנתק...",
  email: "אימייל",
  password: "סיסמה",
  confirm_password: "אימות סיסמה",
  not_found: "לא נמצא",
  error: "שגיאה",
  success: "הצלחה",
  user_registered_successfully: "המשתמש נרשם בהצלחה",
  user_login_successful: "המשתמש התחבר בהצלחה",
  user_logout_successful: "המשתמש התנתק בהצלחה",
  yes: "כן",
  no: "לא",
  wont_share_email: "אנו לא נחלוק באימייל שלך.",
  error_occurred_refresh_page: "אירעה שגיאה. נא לרענן את העמוד",
  select_language: "בחר שפה",
  passwords_dont_match: "הסיסמאות אינן תואמות",
  information: "מידע",
}
export default he;